export const stockData = [
    {
      id: "Twitter Inc",
      name: "TWTR",
      priceUsd: "22.76 USD",
      symbol: "5 sec ago",
      volumeUsd24Hr: "5 sec ago",
      marketCapUsd: "5 sec ago",
      volumeUsdchangePercent24Hr24Hr: "5 sec ago",
    },
    {
      id: "Square Inc",
      name: "SQ",
      priceUsd: "45.28 USD",
      symbol: "10 sec ago",
      volumeUsd24Hr: "10 sec ago",
      marketCapUsd: "10 sec ago",
      changePercent24Hr: "10 sec ago",
    },
    {
      id: "Shopify Inc",
      name: "SHOP",
      priceUsd: "341.79 USD",
      symbol: "3 sec ago",
      volumeUsd24Hr: "3 sec ago",
      marketCapUsd: "3 sec ago",
      changePercent24Hr: "3 sec ago",
    },
    {
      id: "Sunrun Inc",
      name: "RUN",
      priceUsd: "9.87 USD",
      symbol: "4 sec ago",
      volumeUsd24Hr: "4 sec ago",
      marketCapUsdr: "4 sec ago",
      changePercent24Hrr: "4 sec ago",
    },
    {
      id: "Adobe Inc",
      name: "ADBE",
      priceUsd: "300.99 USD",
      symbol: "10 sec ago",
      volumeUsd24Hr: "10 sec ago",
      marketCapUsd: "10 sec ago",
      changePercent24Hr: "10 sec ago",
    },
    {
      id: "HubSpot Inc",
      name: "HUBS",
      priceUsd: "115.22 USD",
      symbol: "12 sec ago",
      volumeUsd24Hr: "12 sec ago",
      marketCapUsd: "12 sec ago",
      changePercent24Hr: "12 sec ago",
    },
  ];